### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory was thrown while watch a keyprefix.

### ISSUE THREAD

**Issue by liukch** [vert-x3/vertx-consul-client#81]
### Questions

When I watch a key prefix, a ```java.lang.OutOfMemoryError: Direct buffer memory``` was thrown.

### Version

Vertx 3.9.3

### Context

My codes like this: 
``` java

    private void initConsulKeyWatch() {
        if (config.consulKeyWatchEnabled()) {
            watch = Watch.keyPrefix(config.getConsulKeyPrefix(), vertx, consulClientOptions)
                .setHandler(res -> {
                    if (res.succeeded()) {
                        final var value = res.nextResult().getList();
                        handleConsulKey(value);
                    } else {
                        log.error("Watch consul key error!", res.cause());
                    }
                }).start();
        }
    }

    private void handleConsulKey(List<KeyValue> list) {
        list.forEach(keyValue -> {
            final var strings = keyValue.getKey().split("/");
            consulKVMap.put(strings[strings.length - 1], keyValue.getValue());
        });
    }

```

### Steps to reproduce

While run code like this, the buffer pool will growth slowly.
After several days, an exception will be thrown
``` java 
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:?]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:755) ~[pirates.jar:?]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:731) ~[pirates.jar:?]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:247) ~[pirates.jar:?]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:215) ~[pirates.jar:?]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147) ~[pirates.jar:?]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356) ~[pirates.jar:?]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) ~[pirates.jar:?]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) ~[pirates.jar:?]
	at io.vertx.core.net.impl.PartialPooledByteBufAllocator.directBuffer(PartialPooledByteBufAllocator.java:92) ~[pirates.jar:?]
	at io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53) ~[pirates.jar:?]
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114) ~[pirates.jar:?]
	at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75) ~[pirates.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777) [pirates.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [pirates.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [pirates.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [pirates.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [pirates.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [pirates.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### Extra

My JVM param is 
``` java 
-ea
-Xms[[.xms]]
-Xmx[[.xmx]]
-Xlog:gc
-XX:+UseG1GC
-XX:MaxGCPauseMillis=50
-XX:ActiveProcessorCount=${attr.cpu.numcores}
-XX:+AlwaysActAsServerClassMachine
```
I don't know weather this had an impact on the problem

**Comment by liukch** [comment]
The JDK which I use is ```Amazon Corretto 11```

**Comment by tsegismont** [comment]
Can you configure the JVM so that it takes a heap dump on out-of-memory error?

Are you able to reproduce on a development machine with Consul in a container?

**Comment by liukch** [comment]
@tsegismont 
Direct buffer out of memory it is buffer pool out of memory,
buffer pool is off-heap memory, so I don't think it's helpful to dump heap.
And I checked the G1 gc log, only heap logs are included, it is perfectly normal.

In My own development machine, it can not be reproduce. I think the server pressure might to low.

**Comment by tsegismont** [comment]
The direct memory is still referenced from heap so by analyzing it you may find some information about where they come from.

**Comment by liukch** [comment]
@tsegismont OK, I'll give it a try.

**Comment by tsegismont** [comment]
Closing, needs more info
